In [1]:
import pandas as pd

# Membaca dua file CSV
res18 = pd.read_csv('resnet18_256x192_data/res18_model_100epoch_256x192.csv')
res34 = pd.read_csv('resnet34_256x192_data/res34_model_100epoch_256x192.csv')

# Menampilkan 5 baris pertama dari masing-masing file
print("===== RESNET-18 MODEL =====")
display(res18.head())

print("\n===== RESNET-34 MODEL =====")
display(res34.head())

===== RESNET-18 MODEL =====


Unnamed: 0  binary_accuracy  f1-score  iou_score      loss  precision  \
0           0         0.811013  0.613032   0.482541  0.421411   0.575155   
1           1         0.910506  0.728675   0.606917  0.259542   0.740540   
2           2         0.931516  0.767582   0.655056  0.193126   0.785535   
3           3         0.942800  0.803069   0.697861  0.162337   0.821693   
4           4         0.950952  0.831953   0.736918  0.138543   0.845166   

     recall  val_binary_accuracy  val_f1-score  val_iou_score  val_loss  \
0  0.838879             0.792415      0.000024       0.000012  0.574821   
1  0.810662             0.843412      0.387518       0.269107  0.382748   
2  0.817364             0.850864      0.576788       0.420514  0.314968   
3  0.827901             0.951252      0.835358       0.742392  0.135614   
4  0.855837             0.947812      0.820283       0.720298  0.137763   

   val_precision  val_recall  
0       0.977273    0.000012  
1       0.705595    0.305737  
2       0.632099    0.558626  
3       0.821421    0.880846  
4       0.815816    0.857941


===== RESNET-34 MODEL =====


Unnamed: 0  binary_accuracy  f1-score  iou_score      loss  precision  \
0           0         0.820806  0.613434   0.477900  0.406407   0.580817   
1           1         0.913744  0.735979   0.614616  0.242206   0.749691   
2           2         0.938369  0.778573   0.672459  0.177892   0.795179   
3           3         0.951538  0.824233   0.728761  0.140657   0.844827   
4           4         0.959621  0.854388   0.766894  0.115675   0.865294   

     recall  val_binary_accuracy  val_f1-score  val_iou_score  val_loss  \
0  0.816369             0.792104      0.003714       0.001900  0.512852   
1  0.806086             0.841468      0.393232       0.279294  0.422489   
2  0.815548             0.945909      0.790065       0.688697  0.152677   
3  0.845772             0.958483      0.846095       0.762039  0.112971   
4  0.869943             0.963693      0.860518       0.778864  0.099012   

   val_precision  val_recall  
0       0.251903    0.002692  
1       0.636385    0.333161  
2       0.804277    0.787396  
3       0.814102    0.884849  
4       0.897644    0.850716

In [2]:
# Misalnya kamu ingin menghapus kolom 'Unnamed: 0'
res18 = res18.drop(columns=['Unnamed: 0', 'loss', 'val_binary_accuracy', 'val_f1-score', 'val_iou_score', 'val_loss', 'val_precision', 'val_recall'])
res34 = res34.drop(columns=['Unnamed: 0', 'loss', 'val_binary_accuracy', 'val_f1-score', 'val_iou_score', 'val_loss', 'val_precision', 'val_recall'])
# Tampilkan hasil setelah drop
display(res18.head())
display(res34.head())


binary_accuracy  f1-score  iou_score  precision    recall
0         0.811013  0.613032   0.482541   0.575155  0.838879
1         0.910506  0.728675   0.606917   0.740540  0.810662
2         0.931516  0.767582   0.655056   0.785535  0.817364
3         0.942800  0.803069   0.697861   0.821693  0.827901
4         0.950952  0.831953   0.736918   0.845166  0.855837

binary_accuracy  f1-score  iou_score  precision    recall
0         0.820806  0.613434   0.477900   0.580817  0.816369
1         0.913744  0.735979   0.614616   0.749691  0.806086
2         0.938369  0.778573   0.672459   0.795179  0.815548
3         0.951538  0.824233   0.728761   0.844827  0.845772
4         0.959621  0.854388   0.766894   0.865294  0.869943

In [3]:
# Asumsi res18 dan res34 sudah ada di memory

# Pilih baris ke 19, 22, 25, ... hingga 94
rows_to_keep = list(range(19, 79, 2))  # Python pakai indeks 0-based, jadi 18 = baris ke-19

res18_filtered = res18.iloc[rows_to_keep]
res34_filtered = res34.iloc[rows_to_keep]

# Tampilkan hasil
display(res18_filtered)
display(res34_filtered)

# Simpan hasil ke file baru
res18_filtered.to_excel("res18_model_sampled.xlsx", index=False)
res34_filtered.to_excel("res34_model_sampled.xlsx", index=False)

print("✅ File tersimpan: res18_model_sampled.xlsx dan res34_model_sampled.xlsx")


binary_accuracy  f1-score  iou_score  precision    recall
19         0.975036  0.903208   0.848098   0.909093  0.922446
21         0.986389  0.945756   0.906336   0.947165  0.951990
23         0.984610  0.936414   0.895220   0.938681  0.947810
25         0.986064  0.943725   0.904394   0.946047  0.952122
27         0.981378  0.924120   0.875402   0.927334  0.935844
29         0.987940  0.953839   0.919640   0.954216  0.956564
31         0.989909  0.963712   0.934272   0.963446  0.968346
33         0.990024  0.960310   0.931806   0.960584  0.964014
35         0.981896  0.933379   0.893404   0.937575  0.945638
37         0.988579  0.950816   0.917563   0.949099  0.959935
39         0.990627  0.957254   0.930363   0.959250  0.961199
41         0.990277  0.967486   0.940441   0.967798  0.969413
43         0.988322  0.954646   0.923366   0.958274  0.962070
45         0.991720  0.967032   0.942133   0.966941  0.973071
47         0.991443  0.961479   0.935069   0.963732  0.968039
49         0.993316  0.975953   0.956174   0.976865  0.978301
51         0.993999  0.981264   0.963791   0.980766  0.982120
53         0.992837  0.962363   0.939854   0.964845  0.973228
55         0.994328  0.975006   0.957624   0.975727  0.980750
57         0.994620  0.976690   0.961322   0.979589  0.979165
59         0.994507  0.976602   0.958376   0.976479  0.980267
61         0.993891  0.977396   0.959011   0.977898  0.979935
63         0.995066  0.984048   0.969153   0.984238  0.984197
65         0.995679  0.985557   0.972105   0.985429  0.986017
67         0.989804  0.958640   0.927878   0.960940  0.963862
69         0.990585  0.962872   0.937738   0.964449  0.965553
71         0.994862  0.981547   0.964936   0.981823  0.982216
73         0.995681  0.978986   0.964656   0.978692  0.982703
75         0.996217  0.985589   0.974228   0.986190  0.987689
77         0.996115  0.982924   0.971017   0.984463  0.985538

binary_accuracy  f1-score  iou_score  precision    recall
19         0.980873  0.933942   0.884917   0.932590  0.942421
21         0.987260  0.954308   0.918802   0.951256  0.963718
23         0.987702  0.950530   0.917355   0.948294  0.965673
25         0.987796  0.957444   0.923139   0.954287  0.965725
27         0.987402  0.956031   0.922264   0.953727  0.963193
29         0.987113  0.954570   0.918517   0.951740  0.961617
31         0.988402  0.963924   0.933994   0.962024  0.970120
33         0.989475  0.965062   0.936614   0.963879  0.969681
35         0.991162  0.970070   0.946147   0.969701  0.974750
37         0.991808  0.973759   0.951874   0.972435  0.975294
39         0.987300  0.955666   0.919733   0.952681  0.962415
41         0.988904  0.958026   0.926970   0.956066  0.968532
43         0.990842  0.973740   0.949145   0.973803  0.973980
45         0.992656  0.975784   0.955524   0.975466  0.978979
47         0.993263  0.979783   0.960956   0.978939  0.981112
49         0.993384  0.980366   0.962305   0.979913  0.981328
51         0.994178  0.980695   0.964727   0.979827  0.981745
53         0.991042  0.969675   0.950517   0.969863  0.979550
55         0.993652  0.978768   0.961153   0.978625  0.981698
57         0.995054  0.983773   0.970600   0.983453  0.984141
59         0.993257  0.968828   0.948635   0.969070  0.977766
61         0.995620  0.983746   0.970835   0.985494  0.984813
63         0.990331  0.961840   0.937037   0.961117  0.972629
65         0.994762  0.978558   0.963570   0.979857  0.983076
67         0.995787  0.981878   0.969693   0.981517  0.987458
69         0.995850  0.985669   0.974572   0.986239  0.988002
71         0.992473  0.973991   0.953757   0.973842  0.978384
73         0.995805  0.983790   0.971580   0.984819  0.986106
75         0.996545  0.990111   0.980499   0.989908  0.990374
77         0.996353  0.981661   0.971390   0.986811  0.984333

✅ File tersimpan: res18_model_sampled.xlsx dan res34_model_sampled.xlsx


In [6]:
import pandas as pd

# Membaca dua file CSV
res18 = pd.read_excel('res18_model_sampled.xlsx')
res34 = pd.read_excel('res34_model_sampled.xlsx')

# Menampilkan 5 baris pertama dari masing-masing file
print("===== RESNET-18 MODEL =====")
display(res18.head())

print("\n===== RESNET-34 MODEL =====")
display(res34.head())

===== RESNET-18 MODEL =====


binary_accuracy  f1-score  iou_score  precision    recall
0         0.975036  0.903208   0.848098   0.909093  0.922446
1         0.986389  0.945756   0.906336   0.947165  0.951990
2         0.984610  0.936414   0.895220   0.938681  0.947810
3         0.986064  0.943725   0.904394   0.946047  0.952122
4         0.981378  0.924120   0.875402   0.927334  0.935844


===== RESNET-34 MODEL =====


binary_accuracy  f1-score  iou_score  precision    recall
0         0.980873  0.933942   0.884917   0.932590  0.942421
1         0.987260  0.954308   0.918802   0.951256  0.963718
2         0.987702  0.950530   0.917355   0.948294  0.965673
3         0.987796  0.957444   0.923139   0.954287  0.965725
4         0.987402  0.956031   0.922264   0.953727  0.963193

In [7]:
import numpy as np
import pandas as pd

# --- langsung pakai semua kolom dari res18 & res34 ---
A = res18.to_numpy(dtype=float)  # (n1 x p)
B = res34.to_numpy(dtype=float)  # (n2 x p)

# (opsional tapi disarankan: pastikan jumlah kolom sama)
assert A.shape[1] == B.shape[1], "Jumlah kolom res18 dan res34 harus sama."

# --- rata-rata per grup & grand mean ---
meanA = A.mean(axis=0)
meanB = B.mean(axis=0)
MEAN  = np.vstack([meanA, meanB])
DATA  = np.vstack([A, B])
GM    = DATA.mean(axis=0)

n1, p = A.shape
n2, p = B.shape
n = [n1, n2]
g = 2

# --- BETWEEN: B = Σ n_k (μ_k - μ)(μ_k - μ)' ---
Between = np.zeros((p, p))
for k in range(g):
    mu_k = MEAN[k, :]
    diff_col = (mu_k - GM).reshape(-1, 1)      # (p x 1)
    Between += n[k] * (diff_col @ diff_col.T)  # (p x p)

# --- WITHIN: W = Σ Σ (x_kj - μ_k)(x_kj - μ_k)' ---
Within = np.zeros((p, p))
for k in range(g):
    Xk  = A if k == 0 else B
    mu_k = MEAN[k, :]
    for j in range(Xk.shape[0]):
        diff_col = (Xk[j, :] - mu_k).reshape(-1, 1)
        Within  += diff_col @ diff_col.T

# --- TOTAL & WILKS' LAMBDA ---
Total  = Within + Between
Lambda = np.linalg.det(Within) / np.linalg.det(Total)

print("Mean A:", meanA)
print("Mean B:", meanB)
print("Grand Mean:", GM)
print("\nBetween:\n", Between)
print("\nWithin:\n", Within)
print("\nTotal:\n", Total)
print("\nWilks' Lambda:", Lambda)


Mean A: [0.99052407 0.96228718 0.93584568 0.96358755 0.96766805]
Mean B: [0.99153497 0.9701995  0.94722741 0.96957475 0.97528713]
Grand Mean: [0.99102952 0.96624334 0.94153654 0.96658115 0.97147759]

Between:
 [[1.53288647e-05 1.19978846e-04 1.72587319e-04 9.07871689e-05
  1.15532215e-04]
 [1.19978846e-04 9.39073036e-04 1.35083894e-03 7.10590117e-04
  9.04269304e-04]
 [1.72587319e-04 1.35083894e-03 1.94315648e-03 1.02217055e-03
  1.30077443e-03]
 [9.07871689e-05 7.10590117e-04 1.02217055e-03 5.37698661e-04
  6.84254372e-04]
 [1.15532215e-04 9.04269304e-04 1.30077443e-03 6.84254372e-04
  8.70755462e-04]]

Within:
 [[0.001133   0.00422682 0.00688757 0.00420062 0.00341981]
 [0.00422682 0.01644384 0.02644075 0.01622758 0.01305943]
 [0.00688757 0.02644075 0.04292502 0.02626963 0.02118908]
 [0.00420062 0.01622758 0.02626963 0.01617111 0.01289759]
 [0.00341981 0.01305943 0.02118908 0.01289759 0.01065591]]

Total:
 [[0.00114833 0.0043468  0.00706016 0.0042914  0.00353534]
 [0.0043468  0.017382

In [8]:
from scipy.stats import f

N_total = n1 + n2
df1 = p
df2 = N_total - p - 1

F_value = ((1 - Lambda) / Lambda) * ((N_total - p - 1) / p)


alpha = 0.05
F_crit = f.isf(alpha, df1, df2)

print(f"df1 = {df1}, df2 = {df2}")
print(f"F hitung = {F_value:.6f}")
print(f"F kritis (alpha={alpha}) = {F_crit:.6f}")


if F_value > F_crit:
    print("Keputusan: Tolak H0 (ada perbedaan signifikan antar 2 grup).")
else:
    print("Keputusan: Gagal menolak H0 (tidak ada perbedaan signifikan).")

df1 = 5, df2 = 54
F hitung = 11.443915
F kritis (alpha=0.05) = 2.386070
Keputusan: Tolak H0 (ada perbedaan signifikan antar 2 grup).
